### ISSUE TITLE
[Question] Help Offer - German Translation

### ISSUE THREAD

**Issue by Der-Floh** [Steviegt6/i-rule-translations#1]
Hey 👋  I wanted to ask if more translations are planned. I found the lang file in the games resources and made my own german translation which replaces the russian one. If you want I could make / improve the german Translation 😉

**Comment by steviegt6** [comment]
You can ping me (Tomat#0001) in the I.RULE Discord for the translator role.

Anyone is free to fork this repository and PR any translations without prior contact.
